# Generated by Django 4.2.24 on 2025-10-04 21:44

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify  # <--- NOUVEL IMPORT


# FONCTION AJOUTÉE POUR PEUPLER LES SLUGS UNIQUEMENT
def create_unique_slugs(apps, schema_editor):
    Product = apps.get_model('store', 'Product')

    # Liste pour vérifier l'unicité des slugs générés
    existing_slugs = set()

    for product in Product.objects.all():
        # 1. Générer le slug initial (basé sur le nom)
        base_slug = slugify(product.name)
        unique_slug = base_slug

        # 2. S'assurer de l'unicité en ajoutant un suffixe (si nécessaire)
        i = 1
        while unique_slug in existing_slugs:
            unique_slug = f"{base_slug}-{i}"
            i += 1

        # 3. Sauvegarder le slug et l'ajouter à la liste des slugs existants
        product.slug = unique_slug
        existing_slugs.add(unique_slug)

        # Sauvegarde seulement le champ slug (update_fields=['slug'])
        product.save(update_fields=['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0004_remove_product_quantity_productvariant_and_more'),
    ]

    operations = [
        # Opération 1: Création du modèle Category (INCHANGÉE)
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        # Opération 2: Ajout du champ is_active (INCHANGÉE)
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif / Visible'),
        ),

        # NOUVELLE SÉQUENCE pour le SLUG (3 étapes)

        # Opération 3: Ajout du champ slug, TEMPORAIREMENT SANS 'unique=True' et avec 'null=True' pour la migration.
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),  # Notez: null=True, pas unique
        ),

        # Opération 4: EXÉCUTION DU CODE PYTHON pour générer et sauvegarder les slugs uniques pour les données existantes.
        migrations.RunPython(create_unique_slugs, migrations.RunPython.noop),

        # Opération 5: Modification du champ slug pour lui AJOUTER la contrainte d'unicité (UNIQUE=True)
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),

        # FIN de la séquence du SLUG

        # Opération 6: Ajout du champ category (INCHANGÉE)
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='products', to='store.category'),
        ),
    ]
