# Generated by Django 4.2.24 on 2025-10-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de paiement'), ('PROCESSING', 'En cours de préparation'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée/Complétée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut de la commande'),
        ),
    ]
