# Generated by Django 4.2.24 on 2025-10-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='contact@laroseboutique.com', max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(default='+33123456789', max_length=20, verbose_name='Numéro de téléphone (WhatsApp)')),
            ],
            options={
                'verbose_name': 'Configuration de la Boutique',
                'verbose_name_plural': 'Configurations de la Boutique',
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
