# Generated by Django 4.2.24 on 2025-10-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'En Attente de Paiement'), ('Processing', 'En Cours de Traitement'), ('Shipped', 'Expédiée'), ('Completed', 'Livrée/Payée'), ('Cancelled', 'Annulée')], default='Pending', max_length=20),
        ),
    ]
