# Generated by Django 4.2.24 on 2025-10-22 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Entrée (Vente, Paiement Reçu)'), ('EXPENSE', 'Sortie (Achat, Frais, Remboursement)')], max_length=10)),
                ('category', models.CharField(choices=[('SALE', 'Vente de Produit'), ('REFUND', 'Remboursement Client'), ('SHIPPING_FEE', 'Frais de Livraison'), ('SUPPLIES', 'Achat de Fournitures/Stock'), ('MISC_INCOME', 'Autre Entrée'), ('MISC_EXPENSE', 'Autre Sortie')], default='SALE', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, verbose_name='Description/Notes')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Financière',
                'verbose_name_plural': 'Transactions Financières',
                'ordering': ('-date',),
            },
        ),
    ]
