# Generated by Django 4.2.24 on 2025-10-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_financialtransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialTransaction',
        ),
    ]
