"""
Django settings for la_rose_boutique project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/#databases
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# UTILISATION DES VARIABLES D'ENVIRONNEMENT DE RENDER
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-g8ib5-4e3f)774fl$i+1f!k2dx!&bgpdy@f2bq1xt599be7hqa')

# SECURITY WARNING: don't run with debug turned on in production!
# DÉFINI PAR LA VARIABLE D'ENVIRONNEMENT DEBUG_MODE sur Render (défaut local = True)
DEBUG = os.environ.get('DEBUG_MODE', 'True') == 'True'

# Permet à toutes les URLs de Render d'accéder au service
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',  # NOUVELLE APP POUR LE CLOUD STORAGE
    'store',
    'orders.apps.OrdersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'la_rose_boutique.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'la_rose_boutique.wsgi.application'


# Database
# ** ATTENTION : Utiliser SQLite en PROD sur Render signifie que la DB sera réinitialisée après chaque déploiement/redémarrage. **
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Kinshasa'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Configuration Statique Générale
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuration MEDIA par défaut (Locale)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuration WhiteNoise/Production et GCS
if not DEBUG:
    # -----------------------------------------------
    # CONFIGURATION GCS (Google Cloud Storage)
    # -----------------------------------------------

    # Indique à Django d'utiliser GCS pour tous les téléversements (MEDIA)
    DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'

    # Récupère le nom du bucket GCS (défini dans les variables d'environnement de Render)
    GS_BUCKET_NAME = os.environ.get("GS_BUCKET_NAME")

    # Définit le chemin d'accès au fichier dans le bucket GCS
    GS_LOCATION = 'media'

    # Construit le MEDIA_URL pour pointer vers l'emplacement GCS
    MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/media/'

    # -----------------------------------------------
    # Configuration Statique (WhiteNoise)
    # -----------------------------------------------
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


