"""
Django settings for la_rose_boutique project.

Generated by 'django-admin startproject' using Django 4.2.24.
"""

from pathlib import Path
import os
from dotenv import load_dotenv # Importe la fonction de lecture

# Charge les variables d'environnement du fichier .env
# Doit être exécuté au début pour rendre les variables disponibles via os.environ.get()
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# LECTURE DE LA CLÉ SECRÈTE DEPUIS OS.ENVIRON (soit .env local, soit Render)
# La valeur 'django-insecure-...' est la valeur par défaut de secours,
# mais elle devrait être fournie par la variable d'environnement dans tous les cas.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-g8ib5-4e3f)774fl$i+1f!k2dx!&bgpdy@f2bq1xt599be7hqa')

# Temporairement à True pour voir l'erreur 500
# IMPORTANT : Laissez DEBUG=True pour l'instant pour continuer à développer en local !
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'storages', # RETIRÉ pour GCS
    'cloudinary_storage', # AJOUTÉ pour Cloudinary
    'cloudinary',         # AJOUTÉ pour Cloudinary
    'store',
    'orders.apps.OrdersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'la_rose_boutique.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'la_rose_boutique.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# Internationalization
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Kinshasa'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# -----------------------------------------------
# CONFIGURATION CLOUDINARY (MEDIA FILES)
# -----------------------------------------------
# Utilise Cloudinary pour stocker tous les fichiers médias (images)
MEDIA_URL = '/media/'

# Lecture de la variable, qui sera disponible car load_dotenv() a été appelé.
CLOUDINARY_URL = os.environ.get('CLOUDINARY_URL')

# Définit Cloudinary comme gestionnaire de fichiers par défaut pour les médias
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuration WhiteNoise/Production
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
